### ISSUE TITLE
Is it possible to set `deno_webview_run` to be non-blocking?

### ISSUE THREAD

**Issue by josh-hemphill** [webview/webview_deno#108]
I noticed `deno_webview_get_recv` is now set to non-blocking, so are there blockers for setting that for `deno_webview_run`?

I tried following the issue threads on the various libs but I'm little lost on what the current status is.

**Comment by MichaelFedora** [comment]
Just setting `_run` to nonblocking makes the webviews unable to run on Windows, at least (it causes a crash). That's all I know, unfortunately.
