### ISSUE TITLE
Doesn't work with `deno compile`

### ISSUE THREAD

**Issue by eezstreet** [webview/webview_deno#110]
Attempting to compile the sample with `deno compile --unsafe` results in an executable that is produced that doesn't actually do anything.

**Comment by sigmaSd** [comment]
`deno compile -A --unstable examples/bind.ts` seems to just work

**Comment by eliassjogreen** [comment]
On intel mac it works for me. Could you please provide more information and confirm that it still does not work. Closing the issue until then.
