### ISSUE TITLE
doc for webview.bind

### ISSUE THREAD

**Issue by elycheikhsmail** [webview/webview_deno#115]
example of how to webview.bind

**Comment by eliassjogreen** [comment]
[View the docs](https://doc.deno.land/https://deno.land/x/webview@0.7.0/mod.ts/~/Webview#bind) and the directory examples in the repository

**Comment by Mqxx** [comment]
[Updated Link to Docs](https://deno.land/x/webview/src/webview.ts?s=Webview&p=prototype.bind)
