### ISSUE TITLE
Window freezes

### ISSUE THREAD

**Issue by Burperino** [webview/webview_deno#133]
I copied and pasted the tutorial code into my project. But when I ran it, the window froze and eventually closed. I didn't get an error message. I'm on windows 10.

**Comment by Burperino** [comment]
This also happens when I run this: "deno run -Ar --unstable https://deno.land/x/webview/examples/local.ts"

**Comment by eliassjogreen** [comment]
What version of deno are you using?

**Comment by Burperino** [comment]
I'm using version 1.23.4
