### ISSUE TITLE
🐛 example not working with deno 1.25.0

### ISSUE THREAD

**Issue by lukas-runge** [webview/webview_deno#134]
Hey folks,

just tested the latest version of deno (on ubuntu) with the example provided in the github README of webview_deno and failed with following error:
```bash
error: Uncaught (in promise) TypeError: Invalid FFI pointer type, expected null, integer or BigInt
    sys.symbols.webview_navigate(
                ^
    at Webview.navigate (https://deno.land/x/webview@0.7.3/src/webview.ts:204:17)
    at https://deno.land/x/webview@0.7.3/examples/local.ts:13:9
```

Is the latest version of webview_deno (v0.7.3 as of now) just not compatible yet, or am I doing something wrong?

Kind regards
@lukas-runge

**Comment by toppair** [comment]
> Is the latest version of webview_deno (v0.7.3 as of now) just not compatible yet, or am I doing something wrong?

There's a [breaking change](https://github.com/denoland/deno/pull/15518) in latest deno release. Also having the same issue.
