### ISSUE TITLE
Example code not working - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by CovertCode** [webview/webview_deno#14]
Deno version: 1.0.0-rc1
OS: Ubuntu 18.04

How to reproduct:
Run this code in terminal:
```
deno run -A -r --unstable https://deno.land/x/webview/examples/multiple.ts
```

Output:
```
INFO downloading deno plugin "deno_webview" from "https://github.com/eliassjogreen/deno_webview/releases/download/0.4.1/libdeno_webview.so"
INFO load deno plugin "deno_webview" from local "/media/USERNAME/Gits/Learning/Deno/.deno_plugins/deno_webview_946da9c58c3e41db8c4204caeac0c747.so"
Segmentation fault (core dumped)
```

**Comment by eliassjogreen** [comment]
Probably an issue with [Boscop/web-view](https://github.com/Boscop/web-view) and not this module. Will probably get fixed by #6

**Comment by jcc10** [comment]
Just tried to run the code to see if it was fixed by #6. (Spoiler: It wasn't)
```
Compile https://deno.land/x/webview/examples/multiple.ts
INFO load deno plugin "deno_webview" from local "/home/[user]/github/deno/.deno_plugins/deno_webview_946da9c58c3e41db8c4204caeac0c747.so"
Segmentation fault (core dumped)
```

**Comment by jcc10** [comment]
Also, this should in some way (tag or issue name) reference that this is a linux issue.

**Comment by iKlsR** [comment]
Same issue on Win 10 latest

**Comment by iKlsR** [comment]
Latest is now working for me!

**Comment by eliassjogreen** [comment]
Awesome! This was most likely because of a version mismatch between the plugin and the deno version.
