### ISSUE TITLE
Uncaught (in promise) TypeError: Deno.openPlugin is not a function

### ISSUE THREAD

**Issue by FridayCandour** [webview/webview_deno#154]
return Deno.openPlugin(file.path);
              ^
    at Module.prepare (https://deno.land/x/plug@0.3.1/plug.ts:81:15)
    at eventLoopTick (ext:core/01_core.js:165:11)
    at async https://deno.land/x/pane@0.2.1/plugin.ts:10:1

 (main) [1]> deno --version
deno 1.32.5 (release, x86_64-unknown-linux-gnu)
v8 11.2.214.9
typescript 5.0.3

**Comment by eliassjogreen** [comment]
You seem to be using an old version of webview, run using `-r` to fix.
