### ISSUE TITLE
Migrate to JSR

### ISSUE THREAD

**Issue by RuiNtD** [webview/webview_deno#165]
Hello. It would be nice if this package could be [migrated to JSR](https://jsr.io/docs/migrate-x-to-jsr), Deno's new preferred registry. I took a look at your deps and it looks like your own dep, Plug, is [already available on JSR](https://jsr.io/@denosaurs/plug), so it should be a quick process.

**Comment by eliassjogreen** [comment]
Voila, [@webview/webview](https://jsr.io/@webview/webview)
