### ISSUE TITLE
Demo from web doesn't work

### ISSUE THREAD

**Issue by jespertheend** [webview/webview_deno#170]
The readme states you can run this for a demo:
```
deno run -Ar --unstable https://deno.land/x/webview/examples/local.ts
```
but when I do so I get
```
error: Relative import path "@denosaurs/plug" not prefixed with / or ./ or ../
```

**Comment by nhrones** [comment]
Same here!  Any help with this.  I had this issue once before with a DWM app.  Don't remember the fix/

**Comment by nhrones** [comment]
Found the problem.  See issue #179 above.
The file /src/ffi.ts/ is still using 'window' rather than 'globalThis' (errors in Deno2)

**Comment by eliassjogreen** [comment]
Hey! Just released a new x version which should fix it
