### ISSUE TITLE
Example of .step()

### ISSUE THREAD

**Issue by khrome83** [webview/webview_deno#20]
How do you use the step function?

**Comment by eliassjogreen** [comment]
The step function returns a boolean that is true if the step was successful otherwise false. So to do the same thing as the run function you would do:
```ts
while(webview.step()) {}
```

**Comment by khrome83** [comment]
Ok cool. I got this running, which allowed me to do things like changing the title.

The issue is it's still running as a blocker, so I can't get messages from other web workers.

**Comment by eliassjogreen** [comment]
Use the ```.run()``` method instead it doesn't block everything.

**Comment by eliassjogreen** [comment]
#5

**Comment by khrome83** [comment]
@eliassjogreen - I tried that first. Actually I had about the same amount of luck...

With `.step()` you can change the title or color of the window while inside the loop. Sort of nice.

With `.run()` actions against the WebView are blocked. So you can't do `.setTitle()` and update the title based on an event in the app.

Both block `server.onmessage` event handler to listen to info from the WebWorker. This is critical because this is how I got around the Mac OS issues. This would be replaced by #12
I assume if that ever worked.

But right now my UI calls `/messages/loaded` and I have a route in the server webwork that listens for that request. Upon receiving it, it then uses `postMessage()` to send data back to the parent, which is the main file that runs the GUI.  The server will execute the console.log().
The main file in the `server.onmessage` the event won't be triggered.

**Comment by eliassjogreen** [comment]
The original issue is solved and this thread has gone stale so closing this in favour of #5
