### ISSUE TITLE
Old webview version in Windows 10 2004

### ISSUE THREAD

**Issue by Ciantic** [webview/webview_deno#37]
What is the correct user agent with Windows 10 2004? For some reason Deno webview uses some old Chromium, even though Windows 10 has newer version (aka Webview2) already installed. Isn't this package using the webview2 provided with the Windows 10 2004 when you have Chrome based Edge installed?

I get this using Deno webview:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19041
```

<details>
<summary>Show example.ts code</summary>

```typescript
import { WebView } from "https://deno.land/x/webview/mod.ts";

const view1 = new WebView({
    title: "Foo",
    url: `data:text/html, <html><script>document.write(navigator.userAgent);</script>`,
    width: 400,
});
await Promise.all([view1.run()]);
```
</details>

 

For instance I have stable Edge and it's user agent is:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36 Edg/83.0.478.54
```

Which I would expect deno webview to report also, but for some reason it's not using that latest webview on my machine.

Why this matters? It matters because the whole idea with Microsoft's Webview2 is that you don't need extra browsers running, it saves a lot of memory, because it uses the same Edge browser user already has installed. This support should be built in the parent C bindings repo: https://github.com/webview/webview, but if this repo does not use those bindings it won't work of course.

**Comment by Ciantic** [comment]
Okay I want to add a note that this a work in progress and depends on https://github.com/webview/webview_rust maturing enough.

**Comment by eliassjogreen** [comment]
Closing this in favour of #6
