### ISSUE TITLE
"webview_deno.dll" failed.

### ISSUE THREAD

**Issue by carnoxen** [webview/webview_deno#38]
downloading plugin "webview_deno" from "https://github.com/webview/webview_deno/releases/download/0.4.2/webview_deno.dll" failed.

how can i fix this?

**Comment by mynuolr** [comment]
modify C:\Users\name\AppData\Local\deno\gen\https\deno.land\x\webview\plugin.ts.js 
![image](https://user-images.githubusercontent.com/3831242/85206442-c01d6c80-b354-11ea-9e75-49e61f7ee0b0.png)

**Comment by carnoxen** [comment]
> modify C:\Users\name\AppData\Local\deno\gen\https\deno.land\x\webview\plugin.ts.js
> ![image](https://user-images.githubusercontent.com/3831242/85206442-c01d6c80-b354-11ea-9e75-49e61f7ee0b0.png)

Still problem. It must be fixed "webview_deno.dll" to "deno_webview.dll" because of no files including "webview_deno" in the release.

**Comment by carnoxen** [comment]
![image](https://user-images.githubusercontent.com/11507165/85214141-575ce100-b3a2-11ea-80cb-d5a951f72f0a.png)

this typos were changed lately, but release files remain uncorrected.

**Comment by Qu4k** [comment]
366f44b72a9ebe51b1bf8abb36736ee924082171 closes the issue

**Comment by carnoxen** [comment]
ok confirmed.
