### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by 00ff0000red** [webview/webview_deno#48]
Tried it out, the example code causes a segmentation fault shortly after starting, without opening the tab. Editing the code to not run the view makes it open a tab in preparation, then stop and seg fault.

**Comment by eliassjogreen** [comment]
What version of deno (`deno -V`) and webview_deno are you using? What os?

**Comment by 00ff0000red** [comment]
Deno 1.1 on Linux OS.
How should I check the webview version?
I imported the master and that segfaulted, so I proceeded to test every version that I could get to compile, he earliest version being 0.4

**Comment by eliassjogreen** [comment]
Hey! Could you try again? Segfaults are most likely caused by mismatched deno and webview versions

**Comment by 00ff0000red** [comment]
What versions are supposed to be compatible with each other? As there definitely isn't a webview 1.1 for Deno 1.1, and 1.4 for 1.4, etc.

**Comment by eliassjogreen** [comment]
[0.4.7](https://github.com/webview/webview_deno/releases/tag/0.4.7) supports deno 1.4.1 (and probably 1.4.0 too).

**Comment by 00ff0000red** [comment]
Oh yeah, I'd already tried out a newer version a few hours ago and got it to work, maybe I'll play around and see what I can do with it.

I'll close this as it is no longer an issue. It should probably be documented what versions are compatible though.
