### ISSUE TITLE
WebView.run() block deno

### ISSUE THREAD

**Issue by IllusionPerdu** [webview/webview_deno#5]
After calling WebView.run() we can no longer call any other function.
example:

```
...
webview1.run()
console.log ("Never print if the window is open");

```

**Comment by eliassjogreen** [comment]
`webview.run()` runs the event loop to completion until the window is closed. If you want to not block deno you can use `webview.step()` and in between steps do stuff. This is a bit messy and not ideal but due to javascripts single threaded nature this is one of the only ways. Another option would be run the `WebView` instance in a `WebWorker` but this currently does not work because of [#3998](https://github.com/denoland/deno/issues/3998)

**Comment by IllusionPerdu** [comment]
Is it not possible to do a theard in the rust code and that the messages is passed in the theard?

WebView.constructor: Starts the theard with the creation of the window.
WibView.command: to send commands to the theard. (setTiltle, setColor, evalJS ...)
WebView.exit: close the window and the theard.

**Comment by eliassjogreen** [comment]
Yes that would be possible but due to the `CWebView` struct pointer not being able to be passed between threads it would make it kind of hard to do (at least for me in rust).

**Comment by IllusionPerdu** [comment]
We have the same problem we do not master the rust.

**Comment by hayd** [comment]
Couldn't all of the plugin ops be async? Would that fix this?

**Comment by eliassjogreen** [comment]
I guess it's worth a try

**Comment by IllusionPerdu** [comment]
It works partially !

This is ok 👍 
```
...
webview1.run()
console.log ("Never print if the window is open");
```

But this not working
```
...
setTimeout(function() {
  console.log("Never print" );
}, 1000);
webview1.run()
```

sorry for the stupid examples;)

**Comment by eliassjogreen** [comment]
Hmm interesting, will look into it later

**Comment by buckle2000** [comment]
The rust side is not synchronous. Search for `loop` in `lib.rs`.

**Comment by eliassjogreen** [comment]
yeah it is a known bug, what needs to be done is probably for the rust code running the webview to be moved to it's own thread which is not currently possible due to the `webview_sys::CWebView` not implementing the correct traits for thread safety. A workaround would be to use a js `Worker` for the webview window.

**Comment by khrome83** [comment]
@eliassjogreen I was not able to get the webview running in a worker due to lack of `window`. I didn't dig much more into it, assumed it was a dead end.

**Comment by eliassjogreen** [comment]
The lack of window is because of the auto unloading of the plugin depending on the window event

**Comment by khrome83** [comment]
Not following. I get this though -
<img width="501" alt="Screen Shot 2020-05-17 at 5 56 01 PM" src="https://user-images.githubusercontent.com/1844739/82162128-c60cc300-9867-11ea-9391-1772342e23b4.png">

### GUI Worker
```
import { WebView } from "https://deno.land/x/webview/mod.ts";

let loaded = false;

const GUI = new WebView({
  title: "Local deno_webview example",
  url: "http://localhost:8000/",
  width: 375,
  height: 667,
  resizable: false,
  debug: true,
  frameless: false,
});

GUI.setColor({ r: 0, g: 0, b: 0, a: 255 });
GUI.setTitle("Name Change");

self.onmessage = (e) => {
    const { action } = e.data;
    if (action === "loaded") {
      loaded = true;
    }
  };  

while (GUI.step()) {
  // GUI.setTitle(`things ${x}`);
  if (loaded) {
    GUI.setColor({ r: 45, g: 55, b: 72, a: 255 });
  }
}
```

### Main FIle
```
const gui = new Worker("./gui.ts", { type: "module", deno: true });
```

So not sure what I am doing wrong that it fails...

**Comment by parliament718** [comment]
Is there any usable solution to this issue? 

> use a js Worker for the webview window

How could I use a js worker if I need to import WebView? Do you have any example?

> The lack of window is because of the auto unloading of the plugin depending on the window event

What does this mean? Can it be fixed?

> If you want to not block deno you can use webview.step()

If this is the only way possible, I'm still not sure how to do it. 
I need to run an http API server (```await app.listen({ port: 8080 })```) **AND** a webview.

This seems like a most basic use case, can this ticket get some attention?

**Comment by parliament718** [comment]
Seems this may not even be a webview specific issue. I wondered if I could run the http server on the webworker instead of the other way around but the result is pretty much the same either way ```Cannot find name "window"```

using worker for webview:
<img width="881" alt="Screen Shot 2020-06-06 at 12 34 58 AM" src="https://user-images.githubusercontent.com/3580270/83936179-f5d82800-a78e-11ea-96aa-cdbd83094ff8.png">

using worker for http server:
<img width="1028" alt="Screen Shot 2020-06-06 at 12 37 53 AM" src="https://user-images.githubusercontent.com/3580270/83936180-f670be80-a78e-11ea-8286-859c03f1e320.png">"

**Comment by eliassjogreen** [comment]
I added the ability to run as a worker along with an example under `examples/worker` although webview-sys building seems to be broken for windows so you will have to build it locally for yourself until #28 is fully functional

**Comment by parliament718** [comment]
@eliassjogreen  Thank you for looking into this. Unfortunately I'm not able to get it working. Now cannot open a webview even without a webworker.

```
import { WebView } from 'https://deno.land/x/webview/mod.ts';

const webview = new WebView({
	url: 'http://localhost:4200',
	width: 600,
	height: 800,
	resizable: true,
	debug: true,
	frameless: false,
});
```
``` deno run -A --unstable --reload server.ts```

<img width="822" alt="Screen Shot 2020-06-06 at 2 13 48 PM" src="https://user-images.githubusercontent.com/3580270/83951628-bc400500-a800-11ea-8e94-94469f64dbb1.png">

If I clone this repo and run

```deno run -A --unstable --reload examples/worker/runner.ts```

it just hangs:

<img width="618" alt="Screen Shot 2020-06-06 at 2 13 25 PM" src="https://user-images.githubusercontent.com/3580270/83951645-fc9f8300-a800-11ea-9702-b95bf61ecced.png">

It seems to hang at the new WebView() call

**Comment by eliassjogreen** [comment]
It not working is probably related to #30, but have you tried building and running it locally as the latest release doesn't contain support for newer deno_core versions.

**Comment by parliament718** [comment]
So downgrading to deno 1.0.3 restored the ability to run the webview without the webworker, however still hangs at the ```new WebView``` call when run as a web worker. Do you mean building and running deno locally or deno_webview?

**Comment by eliassjogreen** [comment]
Building deno_webview locally

**Comment by parliament718** [comment]
I built deno_webview locally but I'm still having trouble running this.

I built using ```deno run -A scripts/build.ts```  

```echo $DENO_WEBVIEW_PLUGIN_BASE```

> file:///Users/user/Documents/code/deno_webview/target/release

```deno run -A scripts/dev.ts examples/multiple.ts```
<img width="743" alt="Screen Shot 2020-06-06 at 8 35 39 PM" src="https://user-images.githubusercontent.com/3580270/83957322-5b7eef80-a835-11ea-96f1-bb7f3f48b3ee.png">

Is deno_webview supposed to be generated in target/release? 

<img width="691" alt="Screen Shot 2020-06-06 at 8 38 36 PM" src="https://user-images.githubusercontent.com/3580270/83957349-bdd7f000-a835-11ea-9563-3a02871794c2.png">

**Comment by parliament718** [comment]
Ok so Im able to run the multiple example using locally deno_webview:

``````deno run -A scripts/dev.ts examples/multiple.ts```

That works (windows popup)

Then I try to run your webworker example

```deno run -A scripts/dev.ts examples/worker/runner.ts```

A window does not popup:

<img width="821" alt="Screen Shot 2020-06-07 at 11 27 09 AM" src="https://user-images.githubusercontent.com/3580270/83973345-c7a03880-a8b3-11ea-8d79-86876a20cb8e.png">

Is deno_webview being loaded from the right place? From the last blue log it seems to loading deno_webview from my local folder "deno_webview/.deno_plugins", is that corrrect?

My ~/.profile file contains:

```
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.deno/bin:$PATH"
export DENO_WEBVIEW_PLUGIN_BASE="file://$HOME/Documents/code/deno_webview/target/release"
```

**Comment by eliassjogreen** [comment]
That should be correct, you could try to delete the .deno_plugins folder before running as it sometimes uses an older cache when running (or at least used to, might not change anything)

**Comment by parliament718** [comment]
Deleted it, didn't help.

Still hands at ```new WebView()``` call

<img width="1089" alt="Screen Shot 2020-06-07 at 11 54 51 AM" src="https://user-images.githubusercontent.com/3580270/83973615-c4a64780-a8b5-11ea-9a01-9c56c7070c3c.png">

**Comment by blubbll** [comment]
also getting this ._.

**Comment by cztomsik** [comment]
> `webview.run()` runs the event loop to completion until the window is closed. If you want to not block deno you can use `webview.step()` and in between steps do stuff. This is a bit messy and not ideal but due to javascripts single threaded nature this is one of the only ways. Another option would be run the `WebView` instance in a `WebWorker` but this currently does not work because of [#3998](https://github.com/denoland/deno/issues/3998)

The trick (for nodejs) was to get `uv_backend_timeout()` in order to know how long you need to wait for next "tick" (it returns the earliest timeout/interval/immediate).

Not sure if you can do that with deno/tokio but I know it worked perfectly for node. Maybe you know who to ask for this.

**Comment by eliassjogreen** [comment]
This issue has finally been resolved by the latest release!
