### ISSUE TITLE
Provide example of building a binary with deno

### ISSUE THREAD

**Issue by MagnusBrzenk** [webview/webview_deno#51]
Sorry, maybe I'm missing something, but I came here expecting to find a hello world example where "Hello World" is written in a deno ts script, and after running some sort of build sequence I get a standalone binary. However, all I see are what look to me like deno scripts. Unless I am failing to understand what this repo does, please provide an example to generate a hello-world binary on the major platforms.

**Comment by eliassjogreen** [comment]
To run a simple hello world kind of example take a look at [README#example](https://github.com/webview/webview_deno#example). If you however want to build and run the whole of webview_deno without using the precompiled binaries you can find instructions on how [here](https://github.com/webview/webview_deno#development).
