### ISSUE TITLE
Outdate /std@0.61.0. Please update Dependencies.

### ISSUE THREAD

**Issue by suchislife801** [webview/webview_deno#54]
Currently, I cannot use webview because the dependencies are outdated. Please update.

Many of them show an outdated std library during the error

The library below is causing this error.
https://deno.land/x/plug@0.0.5/deps.ts

**Comment by eliassjogreen** [comment]
This should be solved by the release of [0.4.7](https://github.com/webview/webview_deno/releases/tag/0.4.7)
