### ISSUE TITLE
Core dump on window close.

### ISSUE THREAD

**Issue by jcc10** [webview/webview_deno#56]
I'm trying to make a [wrapper](https://github.com/jcc10/Simple-Deno-Webview) for webview_deno that (for now) abstracts the annoyances of getting stuff to run and myself have ran into a problem.

The following command works:
```deno run --unstable -A --reload https://raw.githubusercontent.com/jcc10/Simple-Deno-Webview/master/demo.ts```
It starts a oak hello world server, opens a webview, when the webview closes, it exits deno.

The following core dumps:
```deno run --unstable -A --reload https://raw.githubusercontent.com/jcc10/Simple-Deno-Webview/master/failing_demo.ts```
It starts a oak hello world server, opens a webview, when the webview closes it trys to open a new webview (which is when it core dumps) then when the second one closes, it exits deno.

I'm honestly not sure what I'm doing wrong here.

**Comment by jcc10** [comment]
I started work on it before I realized that `window.close()` (#55) doesn't work right now. (I actually did not need that feature)

**Comment by eliassjogreen** [comment]
This issue been resolved by the latest release!
