### ISSUE TITLE
Link CSS/JS and Support Different Pages?

### ISSUE THREAD

**Issue by ebebbington** [webview/webview_deno#58]
Is it possible, or on the roamap to support linking stylesheets, javascripts and supporting links to different pages? eg:

```
const html = `
  <html>
  <head>
    <link rel="stylesheet" href="styles.css">
    <script src="javascripts.js"></scripts>
  </head>
  <body>
    <a href="/users">Users</a> // <-- Will use a 'new' html block
  </body>
  </html>
`;
```

**Comment by eliassjogreen** [comment]
Don't think so, I think the easiest way to achieve this would be to host the pages on localhost or just load them from the filesystem.

**Comment by ebebbington** [comment]
alright thanks :)
