### ISSUE TITLE
Use webview/webview_rust instead of boscop/web-view

### ISSUE THREAD

**Issue by eliassjogreen** [webview/webview_deno#6]
This module will switch to [webview/webview_rust](https://github.com/webview/webview_rust) as soon as possible due to many of [boscop/web-view](https://github.com/Boscop/web-view) problems. This will also make sure to use [webview/webview](https://github.com/webview/webview) code instead of boscop's fork.

**Comment by lemarier** [comment]
Hi @eliassjogreen 

Maybe I can help with it?

**Comment by eliassjogreen** [comment]
Sure thing, currently the development of [tauri-apps/webview_rust](https://github.com/tauri-apps/webview_rust) is kinda slow but please do help!

**Comment by eliassjogreen** [comment]
The bindings exported from [tauri-apps/webview_rust](https://github.com/tauri-apps/webview_rust) should be enough for all we want to implement and more but i will probably wait with releasing the next release until webview_rust has released on crates.

**Comment by lemarier** [comment]
Perfect I'll open a PR

**Comment by abflow** [comment]
I just saw that [webview/webview_rust](https://github.com/webview/webview_rust/releases) has made quite a few releases in the past days.

**Comment by abflow** [comment]
From [next April 13th](https://www.engadget.com/microsoft-edge-legacy-phase-out-232116614.html), Edge will be automatically removed via windows 10 update.

**Comment by abflow** [comment]
There are still today some important bugs on windows with webview/webview.

It seems that tauri-apps are abandonning the webview/webview_rust bindings for a new webview crate built directly in Rust:

https://github.com/tauri-apps/wry
"Cross-platfrom WebView rendering library in Rust that supports all major desktop platforms like Windows 10, macOS, and Linux."

Would that be a better target for deno ?

**Comment by eliassjogreen** [comment]
Yeah, I would love to switch to wry but don't know if it's possible considering it's not within this organizations scope. Might develop something separate for GUIs in the [denosaurs](https://github.com/denosaurs/) organization soon though.
