### ISSUE TITLE
Some way to detect changes in URL

### ISSUE THREAD

**Issue by AZMCode** [webview/webview_deno#61]
I have been trying to build an OAuth app, and in one of the steps, a URL controlled by me must be accessed by the user, and i find the need to create a local http server a bit overkill for just one request. Without a local server however, I cannot get the webview to execute javascript needed to return the access key. This issue could be bypassed by checking the URL on deno's side every time the webview changes URL, and leaves me with the suggestion in the title.

Should this be a feature?

**Comment by eliassjogreen** [comment]
This feature would need to be implemented by [Boscop/web-view](https://github.com/Boscop/web-view) (and later [webview/webview_rust](https://github.com/webview/webview_rust)). You could try running the `external.invoke` method on `onload` and handle the rest from deno. You can find an example of using `external` in the examples folder.

**Comment by AZMCode** [comment]
Alrighty then. Thanks!
