### ISSUE TITLE
a debug tool needed

### ISSUE THREAD

**Issue by lijiajun1979** [webview/webview_deno#66]
like electron,a debug tool needed.

**Comment by eliassjogreen** [comment]
For windows there is [edge devtools](https://pspdfkit.com/blog/2018/edge-devtools-uwp/), can't really speak for the other platforms but try enabling debug and opening the platforms inspector with whatever hotkey is default.

**Comment by wwderw** [comment]
GTK webkit has it as well for Linux.  I don't know about the Qt version.

**Comment by JimaDobes** [comment]
* debugging:
	 - to enable client debugging use 'true' boolean in `new Webview(true);`
	 then once open right-click the view/web page and choose inspect to open the devtools
	 - for deno middleware include either option `--inspect` or `--inspect-brk` then visit url `chrome://inspect` to open the devtools for this (or equivalent), something like:
	 	`deno run -Ar --unstable --inspect-brk ./app.ts`
	 	`deno run -Ar --unstable --inspect ./app.ts`
	 - see the docs for more info https://deno.land/manual/getting_started/debugging_your_code
