### ISSUE TITLE
Clarification about how two-way deno binding works and API proposal

### ISSUE THREAD

**Issue by carragom** [webview/webview_deno#68]
Hi there,

Thanks a lot for the great work on this project. I was excited to see that #12 was completed. Yet I don't quite get how it's suppose to work. Looking at the [example](https://github.com/webview/webview_deno/blob/master/examples/external.ts) on the Webview side seems like we are invoking an external method, but on the Deno side looks like we are just getting an event. Also I could not find an example on how to call a Webview function from Deno. Could anyone shed some light on how this works?.

Assuming this is an event based API, not sure it's, but assuming it's . I think there is a standard, well known, Web API that could fit beautifully. How about making the [Webview](https://github.com/webview/webview_deno/blob/master/webview.ts#L40) class implement the [EventTarget](https://github.com/denoland/deno/blob/v1.6.2/cli/dts/lib.dom.d.ts#L5391) interface (one-way events) or the [EventSource](https://github.com/denoland/deno/blob/v1.6.2/cli/dts/lib.dom.d.ts#L5353) interface (two-way events)?. Instead of having a single callback or loop to route all the events, we could add/remove event listeners for [standard events](https://github.com/denoland/deno/blob/v1.6.2/cli/dts/lib.dom.d.ts#L18371) and/or [custom events](https://github.com/microsoft/TypeScript/issues/28357#issuecomment-711415095). We could even go all out one day and try to implement the entire [Window](https://github.com/denoland/deno/blob/v1.6.2/cli/dts/lib.dom.d.ts#L18472) API 😄. This would make every web programmer out there feel just at home when working with this implementation of Webview and the docs would basically write [itself](https://developer.mozilla.org/en-US/docs/Web/API/Window).

I don't know if what I'm proposing is possible. I would have no idea where to even begin. So apologies if I'm been naive here. All I'm saying is, it would be beautiful if this Webview implementation behaved like a browser Window sharing as much API as possible.
Thanks again for the time and the great work.

**Comment by eliassjogreen** [comment]
Writing a kind of `Window` polyfill is a bit out of the scope of this project but the way the two way bindings work currently is as following:

```typescript
import { Webview } from "../mod.ts";

const html = `
  <html>
  <body>
    <button onclick="external.invoke('A')">A</button>
    <button onclick="external.invoke('B')">B</button>
    <button onclick="external.invoke('C')">C</button>

	<script>
      function remote() {
        // do something
      }
	</script>
  </body>
  </html>
`;

const webview = new Webview(
  { url: `data:text/html,${encodeURIComponent(html)}` },
);

for await (const event of webview.iter()) {
  webview.setTitle(event);
  webview.eval("remote();"); // just like what you would do in a browser inspector console
}

// or as a callback
// await webview.run((event) => {
  webview.setTitle(event);
  webview.eval("remote();");
});

```

**Comment by carragom** [comment]
Thanks for the reply and don't worry about that `Window` thing, it was just a thought.  The code you posted is the same example I linked in my original question so I'll try to write a more concrete question.
When I do `external.invoke('data')` in the Webview side, I'm just sending an event to the Deno side right? I'm not really invoking anything, right?
Thanks.

**Comment by eliassjogreen** [comment]
Correct, `external.invoke('data')` only sends over whatever data as an event to deno land. [webview#305](https://github.com/webview/webview/issues/305) specifies that bi-directional communications using proper JSON RPC is planned but I have not seen any recent development on that front.
