### ISSUE TITLE
Audio in Webview

### ISSUE THREAD

**Issue by wwderw** [webview/webview_deno#69]
This is perhaps beyond the purview of the project, but I was hoping that someone here might be able to get me on the right track.

I've been trying to use Deno to run a webview program on Linux and it uses an audio element.  I keep getting an error in the console about no WebVTT encoder present on the system.  Googling only leads to answer for Android and iOS as that's really where most people it appears think of Webview and not so much on the desktop.

Anybody know of an encoder that webview would be able to recognize to clear the error or another way to clear out there error?

**Comment by AZMCode** [comment]
Although I'm not the developer of this plugin, I suspect this is more of a webview issue than a webview_deno issue. Perhaps try contacting them

**Comment by wwderw** [comment]
It looks like it was related to "subenc" from the GStreamer Bad plugin.  Just installed that plugin and all is right with the simple test that I just did.  Guys over in the Webkit IRC lead me to it.
