### ISSUE TITLE
How to bundle/compile?

### ISSUE THREAD

**Issue by duurland** [webview/webview_deno#71]
Hello.

Is it possible to compile/bundle webview with deno for a single executable?
I've had no luck so far and get a ReferenceError whenever I import webview in the bundle.
Deno is rather new for me so maybe I'm just missing something? 

Example
```
R:\deno\webview-playground>deno compile -Ar -o app.exe --unstable https://deno.land/x/webview/examples/local.ts

[...]

Check https://deno.land/x/webview/examples/local.ts
Bundle https://deno.land/x/webview/examples/local.ts
Compile https://deno.land/x/webview/examples/local.ts
Emit app.exe

R:\deno\webview-playground>app.exe
Download https://github.com/webview/webview_deno/releases/download/0.5.6/webview_deno.dll
error: ReferenceError: joinGlobs is not defined
    at file://$deno$/bundle.js:2975:20
```

**Comment by wwderw** [comment]
Thats an error with latest Deno.  Deno 1.6.3 I think has better luck, just don't have other flags like --lite version, but I was able to compile a program that doesn't compile under later versions.

**Comment by oyzhen** [comment]
The binary compiled by `Deno 1.7.4` running with error: `joinGlobs is not defined`

![image](https://user-images.githubusercontent.com/52534412/108988987-11de7980-76d0-11eb-98f2-ec0e29bc51a6.png)

**Comment by eliassjogreen** [comment]
This is an issue with deno similar to #62, deno issue: [deno#9257](https://github.com/denoland/deno/issues/9257)

**Comment by wwderw** [comment]
0.5.3 (which is what I was using for the program in question (the one referenced in the above post) appears to compile with Deno 1.8.0 that was just released.
