### ISSUE TITLE
Can webview_deno create top-bar menus on macOS?

### ISSUE THREAD

**Issue by callumlocke** [webview/webview_deno#72]
> New to webview and deno. Sorry in advance if this is a dumb question or the wrong place to ask it.

I'm curious about adding native menus.

This is what I see in the MacOS system menu bar when I run the example - it just shows the process name (`deno`, unclickable) and no menus:

![image](https://user-images.githubusercontent.com/250617/109975855-fe946500-7cf2-11eb-84cf-44d4fb97ca8f.png)

Is there any way to add menus to the toolbar when working with webview_deno? Similar to what can be done with [Electron](https://www.electronjs.org/docs/api/menu)?

**Comment by eliassjogreen** [comment]
No this is not currently possible, the main repo is probably a better fit for this kind of question as `webview_deno` only provides bindings to that library.
