### ISSUE TITLE
Hide terminal-window during run

### ISSUE THREAD

**Issue by opvasger** [webview/webview_deno#75]
Hello! I've experimented with compiling to a single binary, and it's working great so far!

I was wondering if it's possible to hide the terminal window while running a compiled executable of an application build on this webview library.

currently, after clicking on the compiled program, a terminal window opens with the text 
`Download https://github.com/webview/webview_deno/releases/download/0.5.6/webview_deno.dll`, followed by the application opening up as expected.

I'd love for the terminal-window to not show up somehow. I've looked into settings within Deno itself, and this module as well, but haven't found any workarounds

Thanks for reading :sunny: let me know if I can help to resolve this somehow

**Comment by AZMCode** [comment]
I believe this to be a shortcoming with deno, and not deno_webview. Might be mistaken tho.

**Comment by GitHubJasper** [comment]
I know this is quite an old post at this point.
But if you want to get this working you could add:
`#![windows_subsystem = "windows"]`
To the top of `cli/main.rs` and compile deno yourself using `cargo build -vv --release`
Resulting binary will be in `target/release/deno.exe`

This creates a deno binary that doesn't use a console.
If you compile your code using that binary the result also won't use a console.

However, make sure that there are no errors before compiling as it won't print anything and just silently fail.
