### ISSUE TITLE
Deno 1.10 support

### ISSUE THREAD

**Issue by Dragonrun1** [webview/webview_deno#79]
deno 1.10.1 (release, x86_64-pc-windows-msvc)
v8 9.1.269.27
typescript 4.2.2

```
error: TS2345 [ERROR]: Argument of type '{ url: string; }' is not assignable to parameter of type 'boolean | undefined'.
  Type '{ url: string; }' is not assignable to type 'true'.
  { url: `data:text/html,${encodeURIComponent(html)}` },
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/webview@0.6.0-pre.0/examples/local.ts:12:3
```

**Comment by eliassjogreen** [comment]
yeah, don't use `0.6.0-pre.0` i had to try some things to make sure they worked on the ci in preparation for `1.10` support.

**Comment by hktr92** [comment]
if you really want to use 0.6, here's an updated version of `local.ts`:
```ts
const webview = new Webview(/* debug: */ true);
webview.navigate(`data:text/html,${encodeURIComponent(html)}`);
await webview.run();
```

it works only on Windows for now, since the release doesn't have compiled libs for linux and macos. 

however, I'd advise you to use 0.5.6 or wait for 0.6 stable release.

**Comment by Dragonrun1** [comment]
NP I was just exploring Webview for possible use in a couple of (mostly) personal projects so decided to try out latest version while I was at it. Thanks for the tip @hktr92 on how to use navigate() I'll give that a try.

**Comment by danaugrs** [comment]
> yeah, don't use 0.6.0-pre.0 i had to try some things to make sure they worked on the ci in preparation for 1.10 support.

The example doesn't work on 0.5.6 either, see https://github.com/webview/webview_deno/issues/81.

**Comment by eliassjogreen** [comment]
This is due to the changes in the internal deno plugin api, 0.5.6 should work if you downgrade ti deno 1.8.3.

**Comment by Dragonrun1** [comment]
Since this is still open/re-opened just wondering if there's an approx. timeline for 0.6 stable? and is there anything I can do in testing it etc? Don't have a lot of time to try helping directly on the code but can do a few git updates and test runs etc if that would help.

**Comment by eliassjogreen** [comment]
Currently the code in the repo is mostly finished and should work if you clone and run it locally. The problem is that the event loop is blocking meaning it would reopen issues like #59, #70, #12, #5 and probably a few more.

**Comment by chovyprognos** [comment]
any update on this?

**Comment by eliassjogreen** [comment]
[#89](https://github.com/webview/webview_deno/issues/89#issuecomment-871334662)
