### ISSUE TITLE
Trying to Close Server When Closing Webview Window

### ISSUE THREAD

**Issue by wwderw** [webview/webview_deno#82]
I haven't been able find much on this and what I have attempted freezes the program and the OS is wanted me to forcefully terminate the entire program after some time passes.

Is there anyway to close the server when closing the webview window?

Currently using webview 0.5.6 and Deno 1.8.3 (as neither the latest stable or canary have been successful using the latest of any of the modules or Deno.  Running an ABC server.

Main reason that I am running a server is due to also using a WASM module as well.

webview.run(({event}) => { 
	switch (event){
		case 'close':
			Deno.exit(); 
                        break;
		case 'domContentLoaded':
			console.log('Program Ready!');
			break;
	}; 
});

Above is what I have to try to run, but it appears not to work, just causes the application to stall until the OS sends a msg to continue or force a kill.

Any thoughts?

Thanks for the help.

**Comment by eliassjogreen** [comment]
Try using the `webview.drop()` function when the close event is recieved.

**Comment by wwderw** [comment]
Same end result.  Only difference is that it immediately greyed out the program window.

**Comment by wwderw** [comment]
Hmmm, tried it with the built in HTTP server that is apart of the std lib for Deno with the same results.

Since I'm really only using the server to bootstrap my app for the wasm module as my logic is a go wasm, is there anyway to disable CORs for the webview programmatically, so I can bypass using the server?

I would speculate that in most instances want an HTTP connection always on, so maybe there isn't a way to close that connection when the webview closes.

**Comment by wwderw** [comment]
Turned out I had to call await app.close() before the window closed.  I did await webview.run() and await app.close() and that appears to give me an instant quit.
