### ISSUE TITLE
Incompatible with latest Deno (v1.11.3)

### ISSUE THREAD

**Issue by John-Dean** [webview/webview_deno#89]
Hi,

The example, and fix documented in #79 do not work for me in the latest Deno versions (v.1.11.3).

The advise on that issue is to downgrade to v1.8.3, however that is not always an option.

Is there an estimated timeline for a new release compatible with the latest Deno?

John

**Comment by eliassjogreen** [comment]
After [deno#10908](https://github.com/denoland/deno/pull/10908) and [deno#11152](https://github.com/denoland/deno/pull/11152) lands.

**Comment by John-Dean** [comment]
Thanks

**Comment by roseMix** [comment]
https://github.com/denoland/deno/pull/10908 landed

**Comment by hironichu** [comment]
Hello, both deno#10908 and deno#11152 have been merged with the latest release of Deno (1.13.0) !

**Comment by eliassjogreen** [comment]
Yes indeed, currently working on some improvements to the new deno ffi to support webview ([#11648](https://github.com/denoland/deno/pull/11648)).

**Comment by tadashiee** [comment]
[#11648](https://github.com/denoland/deno/pull/11648) has been closed. Is there any plans to complete this feature in the future?
I'm sorry I don't have the skills to help, but I'm really looking forward to webview being supported again in deno.

**Comment by Aiko-Suzuki** [comment]
deno 1.16 is out any news?
