### ISSUE TITLE
Main example doesn't work, breaking change in latest build

### ISSUE THREAD

**Issue by justinmchase** [webview/webview_deno#98]
I just ran this command as recommended from the readme:

```sh
deno run -Ar --unstable https://deno.land/x/webview/examples/local.ts
```

Results in this error:

> Check https://deno.land/x/webview/examples/local.ts
> error: TS2345 [ERROR]: Argument of type '{ url: string; }' is not assignable to parameter of type 'boolean | undefined'.
>   Type '{ url: string; }' is not assignable to type 'true'.
>   { url: `data:text/html,${encodeURIComponent(html)}` },
>   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     at https://deno.land/x/webview@0.6.0-pre.0/examples/local.ts:12:3

**Comment by cg219** [comment]
Same here for me. Just tried to run and got the same exact error. Running on Deno 1.16.3

**Comment by gonzoscript** [comment]
Same

deno 1.16.2 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.2
typescript 4.4.2

**Comment by justinmchase** [comment]
There is a known issue with changes to how deno loads native code in the latest version (ffi) its still in progress and apparently needs some additional features in order for this particular library to be updated.

Here is an update on that progress: https://github.com/webview/webview_deno/issues/96#issuecomment-982752094
